# Generated by Django 4.2.6 on 2024-03-25 06:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название услуги')),
                ('description', models.TextField(verbose_name='Напишите описание услуги')),
                ('choices_services', models.CharField(choices=[('Разработка веб сайтов', 'Разработка веб сайтов'), ('Разработка мобильных приложений', 'Разработка мобильных приложений'), ('Разработка DescTopApp', 'Разработка DescTopApp')], max_length=100, verbose_name='Выберите категорию услуг')),
                ('prepaid_expense', models.PositiveIntegerField(default=1500, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Внесите аванс')),
                ('card_number', models.CharField(max_length=16, verbose_name='Напишите номер карты')),
                ('card_month', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Укажите месяц')),
                ('card_year', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(30)], verbose_name='Укажите год')),
                ('card_cvv', models.CharField(max_length=3, verbose_name='Укажите cvv')),
                ('email', models.EmailField(default='@gmail.com', max_length=254, verbose_name='Укажите почту')),
                ('dead_line', models.DateTimeField(default=datetime.datetime(2024, 3, 25, 12, 35, 4, 908800), verbose_name='Укажите дедлайн')),
            ],
        ),
    ]
