# Generated by Django 4.2.6 on 2024-03-25 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='card_month',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Укажите месяц'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 13, 35, 33, 654255), verbose_name='Укажите дедлайн'),
        ),
    ]
