# Generated by Django 4.2.6 on 2024-03-25 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_card_month_alter_service_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='card_year',
            field=models.PositiveIntegerField(default=2000, null=True, verbose_name='Укажите год'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 13, 36, 15, 134723), verbose_name='Укажите дедлайн'),
        ),
    ]
