# Generated by Django 4.2.6 on 2024-03-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='music',
            field=models.FileField(null=True, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
