# Generated by Django 4.2.6 on 2024-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='@gmail.com', max_length=254)),
                ('phone_number', models.CharField(max_length=16)),
                ('map', models.URLField()),
            ],
        ),
    ]
