# Generated by Django 4.2.6 on 2024-03-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtable',
            options={'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='motto',
            options={'verbose_name': 'девиз', 'verbose_name_plural': 'девизы'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'слайд', 'verbose_name_plural': 'слайды'},
        ),
    ]
